CREATE TABLE  "TS_ERROR_CODE" 
   (	"ERROR_CODE_ID" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000) NOT NULL ENABLE, 
	"CAUSE" VARCHAR2(4000) NOT NULL ENABLE, 
	"ACTION" VARCHAR2(4000) NOT NULL ENABLE, 
	"SOURCE_URL" VARCHAR2(1000) NOT NULL ENABLE, 
	 CONSTRAINT "TS_ERROR_CODE_PK" PRIMARY KEY ("ERROR_CODE_ID") ENABLE
   );
/

CREATE TABLE "TS_REF_INTEGRITY"
  (
    "CONSTRAINT_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "DESCRIPTION"     VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CONSTRAINT "TS_REF_INTEGRITY_PK" PRIMARY KEY ("CONSTRAINT_TYPE"));

/
COMMENT ON TABLE "ERROR_FRAMEWORK"."TS_REF_INTEGRITY"
IS
  'http://docs.oracle.com/cd/E11882_01/server.112/e25513/statviews_1046.htm#i1576022';
/
  
  CREATE TABLE "TS_REF_INTEGRITY_ORA"
  (
    "ID"              NUMBER NOT NULL ENABLE,
    "CONSTRAINT_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "ORA_CODE"        NUMBER NOT NULL ENABLE,
    CONSTRAINT "TS_REF_INTEGRITY_ORA_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "TS_REF_INTEGRITY_ORA_TS_R_FK1" FOREIGN KEY ("CONSTRAINT_TYPE") REFERENCES "ERROR_FRAMEWORK"."TS_REF_INTEGRITY" ("CONSTRAINT_TYPE") ENABLE,
    CONSTRAINT "TS_REF_INTEGRITY_ORA_TS_E_FK1" FOREIGN KEY ("ORA_CODE") REFERENCES "ERROR_FRAMEWORK"."TS_ERROR_CODE" ("ERROR_CODE_ID") ENABLE
  );
/

create sequence seq_ts_ref_integrity_ora;
/


  CREATE OR REPLACE TRIGGER "BI_TS_REF_INTEGRIY_ORA" 
   before insert on "ERROR_FRAMEWORK"."TS_REF_INTEGRITY_ORA" 
   for each row 
begin  
         select SEQ_TS_REF_INTEGRITY_ORA.nextval into :NEW."ID" from dual; 
end;

/
ALTER TRIGGER "BI_TS_REF_INTEGRIY_ORA" ENABLE;
  